language: cpp
sudo: false
compiler:
- gcc

install:
- export CXX="g++-4.8" CC="gcc-4.8"

addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - ubuntu-sdk

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_script:
- ls
- $CXX --version

script: qmake "QMAKE_CC=$CC" "QMAKE_CXX=$CXX" "QMAKE_CXXFLAGS+=-std=c++11" demo/QtGoodiesDemo/QtGoodiesDemo.pro && make

notifications:
  email: false
